import React,{useEffect,useMemo,useState}from'react';

const API=import.meta.env.VITE_API_URL||'/api';
const COLORS=['#1769c2','#2d8bea','#58a8f5','#84c1f5','#9db9dc','#b8c7d9','#d4dee9'];
const ACTION_LABELS={match:'Candidate matches generated','team-builder':'Team recommendation created','skill-gap':'Skill-gap analysis completed','upload-cv':'New candidate CV processed','rag-search':'Knowledge search completed',ask:'TalentAI request completed',ask_clarification:'TalentAI requested missing information',ask_reset:'TalentAI conversation reset',ask_scope_guard:'Out-of-scope request handled',ask_people_count:'People count completed',ask_followup:'TalentAI follow-up completed'};

function Metric({icon,tone,value,label,note}){return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><div><b>{Number(value).toLocaleString()}</b><p>{label}</p><small><i/> {note}</small></div></article>}

function donutGradient(rows=[]){let cursor=0;let stops=[];rows.forEach((row,index)=>{let end=cursor+row.percent;stops.push(`${COLORS[index%COLORS.length]} ${cursor}% ${end}%`);cursor=end});if(cursor<100)stops.push(`#dce6f1 ${cursor}% 100%`);return `conic-gradient(${stops.join(',')})`}

export default function TalentDashboard({navigate}){
 const[data,setData]=useState(),[error,setError]=useState('');
 useEffect(()=>{fetch(API+'/dashboard').then(r=>r.ok?r.json():Promise.reject(new Error('Dashboard request failed'))).then(setData).catch(()=>setError('Dashboard data could not be loaded. Check that the API service is running.'))},[]);
 const maxSkill=useMemo(()=>Math.max(1,...(data?.top_skills||[]).map(x=>x.count)),[data]);
 const counts=data?.counts||{};const today=new Intl.DateTimeFormat('en',{weekday:'long',month:'short',day:'numeric',year:'numeric'}).format(new Date());
 if(error)return <div className="dashboard-page"><div className="dashboard-error"><h1>Dashboard unavailable</h1><p>{error}</p></div></div>;
 if(!data)return <div className="dashboard-page"><div className="dashboard-loading">Loading verified workforce data…</div></div>;
 return <div className="dashboard-page">
  <div className="dashboard-heading"><div><p className="eyebrow">WORKFORCE INTELLIGENCE</p><h1>Workforce Dashboard</h1><p>Here’s an overview of your workforce data and AI-powered workflows.</p></div><span className="date-chip">▣ &nbsp; {today}</span></div>
  <div className="metric-grid"><Metric icon="♟" tone="blue" value={counts.employees} label="Employees" note="Live employee records"/><Metric icon="●" tone="teal" value={counts.candidates} label="Candidate profiles" note="Evidence-grounded CVs"/><Metric icon="▤" tone="purple" value={counts.courses} label="Training courses" note="Curated learning links"/><Metric icon="◆" tone="amber" value={counts.projects} label="Project briefs" note="Available for team matching"/></div>
  <div className="insight-grid">
   <article className="dashboard-card department-card"><div className="card-title"><h2>Employees by Department</h2><button onClick={()=>navigate('people')}>View details →</button></div><div className="department-content"><div className="donut" style={{background:donutGradient(data?.departments)}}><span><b>{Number(counts.employees||0).toLocaleString()}</b><small>Employees</small></span></div><div className="legend">{data?.departments?.map((row,i)=><div key={row.name}><i style={{background:COLORS[i%COLORS.length]}}/><span>{row.name}</span><b>{row.count}</b><small>{row.percent}%</small></div>)}</div></div></article>
   <article className="dashboard-card skills-card"><div className="card-title"><h2>Top Skills (Employees)</h2><button onClick={()=>navigate('people')}>View all →</button></div>{data?.top_skills?.map(row=><div className="skill-row" key={row.name}><span>{row.name}</span><div><i style={{width:`${100*row.count/maxSkill}%`}}/></div><small>{row.count}</small></div>)}</article>
   <article className="dashboard-card assistant-card"><span className="assistant-spark">✦</span><h2>Ask TalentAI</h2><p>Find candidates, build complementary teams, or ask any HR-related question.</p><button className="assistant-input" onClick={()=>navigate('ask')}><span>⌕ &nbsp; What would you like to know?</span><b>→</b></button><small>Try asking:</small><button className="suggestion" onClick={()=>navigate('ask','Find the top 3 candidates for a Senior Data Engineer requiring Python, AWS and SQL.')}>→ &nbsp; Find top candidates for a Senior Data Engineer</button><button className="suggestion" onClick={()=>navigate('ask','Build a 4-person team for a 6-month NLP project requiring Python, NLP, RAG and AWS.')}>→ &nbsp; Build an available NLP project team</button></article>
  </div>
  <article className="dashboard-card quick-section"><div className="card-title"><div><h2>Quick Actions</h2><p>Jump to the main workflows</p></div></div><div className="action-grid"><button className="action-card blue" onClick={()=>navigate('match')}><i>◎</i><span><b>Match Candidates</b><small>Find the strongest documented matches</small></span><strong>→</strong></button><button className="action-card teal" onClick={()=>navigate('team')}><i>♟</i><span><b>Build a Team</b><small>Create a complementary project team</small></span><strong>→</strong></button><button className="action-card purple" onClick={()=>navigate('gap')}><i>▥</i><span><b>Analyze Skill Gaps</b><small>Identify gaps and training options</small></span><strong>→</strong></button><button className="action-card amber" onClick={()=>navigate('ask')}><i>◌</i><span><b>Ask TalentAI</b><small>Use natural language for insights</small></span><strong>→</strong></button></div></article>
  <div className="bottom-grid"><article className="dashboard-card activity-card"><div className="card-title"><h2>Recent Activity</h2><span>Audit trail</span></div>{data.recent_activity?.length?data.recent_activity.map((row,i)=><div className="activity-row" key={i}><i>{['●','▤','♟','◎','✦'][i%5]}</i><span><b>{ACTION_LABELS[row.action]||row.action.replaceAll('_',' ')}</b><small>{row.citations?`${row.citations} grounded source IDs recorded`:'No record sources required'}</small></span><em>{row.citations?'Grounded':'Logged'}</em></div>):<p className="empty-state">Run a workflow to populate the activity trail.</p>}</article><article className="dashboard-card status-card"><div className="card-title"><h2>System Status</h2><span className="live-badge">● Connected</span></div><div className="status-row"><i>✓</i><span><b>{data.database.dialect==='postgresql'?'PostgreSQL connected':'Database connected'}</b><small>{data.database.dialect} operational data source</small></span></div><div className="status-row"><i>✓</i><span><b>Evidence-grounded matching policy</b><small>Unknown fields are excluded from assessable weights</small></span></div><div className="status-row"><i>✓</i><span><b>Workflow API responding</b><small>Dashboard summary and audit trail loaded successfully</small></span></div></article></div>
 </div>
}
